version: "3"

volumes: # 自定义数据卷，位于宿主机/var/lib/docker/volumes内
  myproject_db_vol: # 定义数据卷同步容器内mysql数据
  myproject_redis_vol: # 定义数据卷同步redis容器内数据

services:
  db:
    image: mysql:8.0.33
    environment:
       - MYSQL_ROOT_PASSWORD=123456 # 数据库密码
       - MYSQL_DATABASE=oneword # 数据库名称
       - MYSQL_USER=link # 数据库用户名
       - MYSQL_PASSWORD=123456 # 用户密码

    volumes:
       - myproject_db_vol:/var/lib/mysql:rw # 挂载数据库数据, 可读可写
       - ./compose/mysql/sqldata:/opt:rw
       - ./compose/mysql/conf/my.cnf:/etc/mysql/my.cnf # 挂载配置文件
       - ./compose/mysql/init:/docker-entrypoint-initdb.d/ # 挂载数据初始化sql脚本
    ports:
       - "3306:3306" # 与配置文件保持一致，映射端口
    restart: always

  web:
    build: ./inaword_backend # 使用目录下的Dockerfile
    ports:
       - "9000:9000"
    expose:
       - "9000"
    volumes:
       - ./inaword_backend:/var/api/inaword_backend # 挂载项目代码
       - ./compose/uwsgi:/tmp # 挂载uwsgi日志
    links:
       - db
    depends_on: # 依赖关系
       - db
    environment:
       - DEBUG=True
    restart: always
    tty: true
    stdin_open: true

  nginx:
    build: ./compose/nginx
    ports:
       - "80:80"
       - "8000:8000"
    expose:
       - "80"
       - "8000"
    volumes:
       - ./compose/nginx/log:/var/log/nginx # 挂载日志
    links:
       - web
    depends_on:
       - web
    restart: always
